# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default=b'', max_length=255, null=True, verbose_name=b'Asunto')),
                ('message', models.TextField(blank=True, default=b'', null=True, verbose_name=b'Mensaje')),
            ],
            options={
                'ordering': ['-subject', '-message'],
                'db_table': 'contact',
                'verbose_name_plural': 'Contactos',
            },
        ),
    ]
