# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=b'', max_length=100, verbose_name=b'Nombre')),
                ('apellido', models.CharField(blank=True, default=b'', max_length=100, null=True, verbose_name=b'Apellido')),
                ('edad', models.PositiveIntegerField(blank=True, null=True, verbose_name=b'Edad')),
                ('genero', models.CharField(blank=True, choices=[(b'hombre', b'Hombre'), (b'mujer', b'Mujer'), (b'otros', b'Otros')], default=b'otros', max_length=30, null=True, verbose_name=b'Estado')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name=b'Salario')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, verbose_name=b'Fecha de creaci\xc3\xb3n')),
                ('fecha_de_actualizacion', models.DateTimeField(auto_now=True, verbose_name=b'Fecha de actualizaci\xc3\xb3n')),
            ],
            options={
                'ordering': ['-nombre'],
                'db_table': 'estudiantes',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
    ]
