# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20171122_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='slug',
            field=models.SlugField(default=b'', max_length=100, verbose_name=b'Slug'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='facultad',
            field=models.CharField(blank=True, choices=[(b'0', b'Facultad de Sistemas'), (b'1', b'Facultad de Industrial'), (b'2', b'Facultad de Civil'), (b'3', b'Facultad de El\xc3\xa9ctrica')], default=b'0', max_length=30, null=True, verbose_name=b'G\xc3\xa9nero'),
        ),
    ]
