# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20171123_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='slug',
            field=models.SlugField(default=b'', max_length=100, unique=True, verbose_name=b'Slug'),
        ),
    ]
