# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_asignatura_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='slug',
            field=models.SlugField(default=b'', max_length=100, verbose_name=b'Slug'),
        ),
    ]
